version: '3.8'

services:
  web:
    build:
      context: docker/prod
    container_name: api_web_prod
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - prod.env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres_db

  adminer:
    image: adminer:4.8.1-standalone
    container_name: api_adminer
    env_file:
        - dev.env
    ports:
      - 8032:8032

  postgres_db:
    build:
      context: docker/prod
      dockerfile: Postgres.Dockerfile
    image: postgres:13-alpine
    container_name: api_pgsql_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - prod.env
    ports:
      - 5432:5432


volumes:
  postgres_data:
